blank_issues_enabled: false
contact_links:
  - name: Issue of Standard Registry
    url: https://github.com/aquaproj/aqua-registry/issues
    about: Please report issues about aqua Standard Registry
  - name: NotebookLM
    url: https://notebooklm.google.com/notebook/874e89e4-66a1-459a-82c9-923b81501a71
    about: Please ask questions freely
  - name: Discord
    url: https://discord.gg/CBGesz8yBX
    about: Please ask questions freely
