---
# Separate the workflow for actionlint to other workflows, because if a workflow for actionlint is broken actionlint isn't run
name: actionlint
on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - aqua/imports/actionlint.yaml
      - aqua/imports/reviewdog.yaml
jobs:
  actionlint:
    uses: suzuki-shunsuke/actionlint-workflow/.github/workflows/actionlint.yaml@813a6d08c08cfd7a08618a89a59bfe78e573597c # v1.0.1
    with:
      aqua_version: v2.29.2
      aqua_policy_allow: true
    permissions:
      pull-requests: write
      contents: read
