---
name: Debug with action-tmate
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: false
        default: windows-latest
      pr_number:
        required: false
      ref:
        required: false
permissions: {}
jobs:
  action-tmate:
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{inputs.ref}}

      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.25.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.22.1

      # The default vim doesn't work well, so we install the latest vim ourselves.
      - uses: rhysd/action-setup-vim@0aa9cbac67d0fe3c5e3cde29caf745a721b19479 # v1.3.1

      - uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14
        with:
          limit-access-to-actor: true # SSH Key is required
        env:
          GITHUB_TOKEN: ${{github.token}} # Pass GitHub Token to shell session
