---
name: Debug with action-tmate
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: false
        default: windows-latest
      pr_number:
        required: false
      ref:
        required: false
permissions: {}
jobs:
  action-tmate:
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: ${{inputs.ref}}

      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          aqua_version: v2.12.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.21.1

      # The default vim doesn't work well, so we install the latest vim ourselves.
      - uses: rhysd/action-setup-vim@015df8c5b8dabdca7febe31bb66c156c0d780374 # v1.2.15

      - uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14
        with:
          limit-access-to-actor: true # SSH Key is required
        env:
          GITHUB_TOKEN: ${{github.token}} # Pass GitHub Token to shell session
