---
name: Debug with action-tmate
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: false
        default: windows-latest
      pr_number:
        required: false
      ref:
        required: false
permissions: {}
jobs:
  action-tmate:
    timeout-minutes: 360
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          ref: ${{inputs.ref}}

      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.36.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.23.2

      # The default vim doesn't work well, so we install the latest vim ourselves.
      - uses: rhysd/action-setup-vim@acff3bc31a82af69a26f90af710926fdab04d00e # v1.3.5

      - uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14
        with:
          limit-access-to-actor: true # SSH Key is required
        env:
          GITHUB_TOKEN: ${{github.token}} # Pass GitHub Token to shell session
