---
name: integration-test
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AQUA_LOG_LEVEL: debug
      AQUA_LOG_COLOR: always
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.3.0
      with:
        go-version: '1.19.1'
        cache: true

    - run: go install ./cmd/aqua
    - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
    - run: echo "AQUA_GLOBAL_CONFIG=$PWD/tests/aqua-global.yaml:$PWD/tests/aqua-global-2.yaml" >> "$GITHUB_ENV"
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: echo "local,aquaproj/aqua-installer" | aqua -c tests/aqua-global.yaml g -f -
    - run: aqua g x-motemen/ghq aquaproj/aqua-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq aquaproj/aqua-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
      env:
        AQUA_LOG_COLOR: always
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
      env:
        AQUA_PROGRESS_BAR: "true"
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: tfenv --version
    - run: aqua -c tests/aqua-global.yaml g local,kubernetes-sigs/kustomize
    - run: btop -v
    - run: btop -v
      env:
        AQUA_EXPERIMENTAL_X_SYS_EXEC: "true"
    - run: wire --help
    - run: gox --help
    - run: bats -v
    - run: github-compare -v
    - run: terrafmt version

    - name: output bash completion
      run: aqua completion bash
    - name: output zsh completion
      run: aqua completion zsh

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - name: add duplicated package
      run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - name: "Test generate-registry"
      run: aqua gr cli/cli
    - name: "Test generate-registry (emoji)"
      run: aqua gr hmarr/codeowners
    - name: "Test generate-registry (rust)"
      run: aqua gr XAMPPRocky/tokei

    - name: "test version_source: github_tag"
      run: aqua -c aqua-global.yaml g local,mitchellh/gox
      working-directory: tests

    - name: test aqua cp
      run: aqua cp actionlint golangci-lint
    - name: test aqua cp
      run: dist/actionlint -version
    - name: test aqua cp
      run: dist/golangci-lint version

    # Test if global configuration files are read in `aqua list` and `aqua g`
    - run: aqua g suzuki-shunsuke/cmdx
      working-directory: /tmp
    - run: aqua list
      working-directory: /tmp

    - run: aqua-installer -v v0.8.1 -i /tmp/aqua

  build-windows:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AQUA_LOG_LEVEL: debug
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.3.0
      with:
        go-version: '1.19.1'
        cache: true

    - run: go install ./cmd/aqua
    - run: echo "$HOME/AppData/Local/aquaproj-aqua/bin" >> "$GITHUB_PATH"
    - run: echo "AQUA_GLOBAL_CONFIG=$PWD/tests/aqua-global.yaml:$PWD/tests/aqua-global-2.yaml" >> "$GITHUB_ENV"
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: aqua g x-motemen/ghq aquaproj/aqua-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq aquaproj/aqua-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
      env:
        AQUA_PROGRESS_BAR: "true"
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: aqua -c tests/aqua-global.yaml g local,kubernetes-sigs/kustomize
    - run: wire --help
    - run: gox --help
    - run: github-compare -v
    - run: terrafmt version

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - name: "Test generate-registry"
      run: aqua gr cli/cli
    - name: "Test generate-registry (rust)"
      run: aqua gr XAMPPRocky/tokei

    - name: "test version_source: github_tag"
      run: aqua -c aqua-global.yaml g local,mitchellh/gox
      working-directory: tests

    # Test if global configuration files are read in `aqua list` and `aqua g`
    - run: aqua g suzuki-shunsuke/cmdx
      working-directory: ${{ env.HOME }}
    - run: aqua list
      working-directory: ${{ env.HOME }}

    - name: test aqua cp
      run: aqua cp actionlint golangci-lint
    - name: test aqua cp
      run: dist/actionlint -version
    - name: test aqua cp
      run: dist/golangci-lint version

  build-windows-pwsh:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AQUA_LOG_LEVEL: debug
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.3.0
      with:
        go-version: '1.19.1'
        cache: true

    - run: go install ./cmd/aqua
    - run: echo "$HOME\AppData\Local\aquaproj-aqua\bat" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: echo "AQUA_GLOBAL_CONFIG=$PWD\tests\aqua-global.yaml;$PWD\tests\aqua-global-2.yaml" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - run: echo "standard,kubernetes-sigs/kind" | aqua g -f -
    - run: echo "x-motemen/ghq" | aqua g -f -
    - run: aqua g x-motemen/ghq aquaproj/aqua-installer
    - run: echo cli/cli | aqua g -f - x-motemen/ghq aquaproj/aqua-installer

    - run: aqua list
    - run: aqua i -l -a
      working-directory: tests
    - run: cmdx -v
      working-directory: tests
    - run: aqua i --test
      working-directory: tests
    - run: aqua which golangci-lint
      working-directory: tests
    - run: aqua which go
    - run: golangci-lint version
    - run: kind version
      working-directory: tests
    - run: kind version
    - run: restic version
      env:
        AQUA_PROGRESS_BAR: "true"
    - run: migrate -version
    - run: ghq -version
    - run: gh version
    - run: aqua -c tests/aqua-global.yaml g local,kubernetes-sigs/kustomize
    - run: wire --help
    - run: gox --help
    - run: github-compare -v
    - run: terrafmt version

    - run: aqua g -i suzuki-shunsuke/tfcmt
      working-directory: tests
    - run: git diff aqua.yaml
      working-directory: tests

    - name: "Test generate-registry"
      run: aqua gr cli/cli
    - name: "Test generate-registry (rust)"
      run: aqua gr XAMPPRocky/tokei

    - name: "test version_source: github_tag"
      run: aqua -c aqua-global.yaml g local,mitchellh/gox
      working-directory: tests

    # Test if global configuration files are read in `aqua list` and `aqua g`
    - run: aqua g suzuki-shunsuke/cmdx
      working-directory: ${{ env.HOME }}
    - run: aqua list
      working-directory: ${{ env.HOME }}

    - name: test aqua cp
      run: aqua cp actionlint golangci-lint
    - name: test aqua cp
      run: dist/actionlint -version
    - name: test aqua cp
      run: dist/golangci-lint version
