---
name: Integration Test on macOS
on: workflow_dispatch

env:
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  integration-test-macos:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: go install ./cmd/aqua
      - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
      - run: aqua policy allow
      - run: aqua i -l
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: aws-vault --version
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: aqua gr 99designs/aws-vault
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: s3deploy -V
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: aqua gr bep/s3deploy
        env:
          GITHUB_TOKEN: ${{github.token}}
