---
name: Integration Test on macOS
on: workflow_dispatch

env:
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua/policy.yaml
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  integration-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.20.3
          cache: true
      - run: go install ./cmd/aqua
      - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "$GITHUB_PATH"
      - run: aqua i -l
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: aws-vault --version
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: aqua gr 99designs/aws-vault
        env:
          GITHUB_TOKEN: ${{github.token}}
