---
name: test GoReleaser
on: workflow_call
jobs:
  test-goreleaser:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.55.0
      - run: goreleaser check
      # Build is too slow for a test
      # - run: goreleaser release --snapshot
