---
name: go-mod-tidy
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  go-mod-tidy:
    uses: suzuki-shunsuke/go-mod-tidy-workflow/.github/workflows/go-mod-tidy.yaml@8facac38f5b2008648c14e31c632c3a709439b9c # v0.1.1
    with:
      go-version: 1.21.1
      aqua_version: v2.11.0
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
    permissions:
      contents: read
