---
name: go-mod-tidy
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true
jobs:
  go-mod-tidy:
    uses: suzuki-shunsuke/go-mod-tidy-workflow/.github/workflows/go-mod-tidy.yaml@79af8ebcd2dea45c27303b09192be80f7a35a37a # v1.1.0
    with:
      go-version: 1.22.6
      aqua_version: v2.33.0
    secrets:
      gh_app_id: ${{secrets.gh_app_id}}
      gh_app_private_key: ${{secrets.gh_app_private_key}}
    permissions:
      contents: read
